name: diario as - selenium
# run-name: selenium - ${{ inputs.os }} - ${{ inputs.browser }}
run-name: selenium - macos-latest - ${{ inputs.browser }}

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Elige el navegador
        required: true
        options:
          - chrome
          - safari
      allure:
        type: boolean
        description: Publicar en Allure
        default: true
      extent:
        type: boolean
        description: Generar reporte Extent
        default: true
      pdf:
        type: boolean
        description: Generar PDF
        default: true
      recorder:
        type: boolean
        description: Grabar la ejecución
        default: true

jobs:
  selenium:
    # runs-on: ${{ github.event.inputs.os }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run Selenium with Maven
        run: mvn clean test -Dbrowser=${{ github.event.inputs.browser }} -Ddocker=false -Dproxy=${{ secrets.PROXY_HOST_PORT }}

      - name: Generate artifact for Extent PDF
        uses: actions/upload-artifact@v3
        if: always()
        with:
          pdf: true
          name: report_pdf
          path: ./extent-reports/pdf

      - name: Generate artifact for ExtentReports Spark HTML
        uses: actions/upload-artifact@v3
        if: always()
        with:
          extent: true
          name: report_html
          path: ./extent-reports/spark

      - name: Generate artifact for Allure Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          allure: true
          name: report_allure
          path: ./allure-results

      - name: Generate artifact for video recording
        uses: actions/upload-artifact@v3
        if: always()
        with:
          recorder: true
          name: report_video
          path: ./test-recordings

  allure:
    needs: selenium
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          allure: true
          name: report_allure
          path: ./allure-results
            
      - name: Get AllureReports history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          allure: true
          ref: allure
          path: allure

      - name: Get AllureReports results
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure: true
          allure_results: ./allure-results
          gh_pages: allure
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10

      - name: Prepare AllureReports deploy to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        with:
          allure: true
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: allure
          PUBLISH_DIR: allure-history